### ISSUE TITLE
Could not find a version of package alister/todotxt-parser matching your minimum-stability (stable).

### ISSUE THREAD

**Issue by chung1905** [alister/todotxt-parser#1]
Hello,

I got this error when require this package:

![image](https://user-images.githubusercontent.com/16518833/102053912-19a1b800-3e1b-11eb-8a27-3759c6ad4086.png)

I ran this in docker container with image: php:7.4-fpm-alpine with composer 2.0.8

Thanks for the package.

**Comment by alister** [comment]
Hi!  This was just a project I did for fun, so it's a little unfinished around the edges. The code is good (and tested) - but I'd not added CI or tagged it - which is what it means with the message.
I'll see what I can do in the next couple of days to add some Github actions for tests, and as soon as they are in place, I think it would be good to mark as v1.0.0

**Comment by alister** [comment]
I've added tests - for PHP 7.4 & 8.0 (the versions are fetched from the composer.json file, `require:php` settings), and tagged a v1.0.0. It's also available via Packagist - https://packagist.org/packages/alister/todotxt-parser#v1.0.0
